server:
  port: 7003

#Eureka
eureka:
  instance:
    hostname: eureka7003.com
  client:
    register-with-eureka: true  #表示是否向Eureka注册中心注册自己
    fetch-registry: false #false表示自己为注册中心
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7002.com:7002/eureka/